/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-01-25 14:31:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.jspshop.util.PageManager;
import org.apache.ibatis.session.SqlSession;
import com.jspshop.mybatis.MybatisConfig;
import com.jspshop.domain.Product;
import java.util.List;
import com.jspshop.repository.ProductDAO;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


	ProductDAO productDAO=new ProductDAO();
	MybatisConfig mybatisConfig=MybatisConfig.getInstance();
	PageManager pm=new PageManager();

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/admin/inc/sidebar_right.jsp", Long.valueOf(1674045568000L));
    _jspx_dependants.put("/admin/inc/footer_link.jsp", Long.valueOf(1674123080000L));
    _jspx_dependants.put("/admin/inc/footer.jsp", Long.valueOf(1674043732000L));
    _jspx_dependants.put("/admin/inc/header_link.jsp", Long.valueOf(1674212252000L));
    _jspx_dependants.put("/admin/inc/preloader.jsp", Long.valueOf(1674044051000L));
    _jspx_dependants.put("/admin/inc/sidebar_left.jsp", Long.valueOf(1674044524000L));
    _jspx_dependants.put("/admin/inc/navbar.jsp", Long.valueOf(1674045009000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.jspshop.mybatis.MybatisConfig");
    _jspx_imports_classes.add("com.jspshop.repository.ProductDAO");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.jspshop.domain.Product");
    _jspx_imports_classes.add("com.jspshop.util.PageManager");
    _jspx_imports_classes.add("org.apache.ibatis.session.SqlSession");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write('\n');

	SqlSession sqlSession=mybatisConfig.getSqlSession();

	productDAO.setSqlSession(sqlSession);
	List<Product> productList=productDAO.selectAll();
	
	pm.init(productList, request);

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"utf-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("  <title>상품 등록 </title>\n");
      out.write("\n");
      out.write("<!-- Google Font: Source Sans Pro -->\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback\">\n");
      out.write("<!-- Font Awesome -->\n");
      out.write("<link rel=\"stylesheet\" href=\"/admin/plugins/fontawesome-free/css/all.min.css\">\n");
      out.write("<!-- Ionicons -->\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css\">\n");
      out.write("<!-- Tempusdominus Bootstrap 4 -->\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"/admin/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css\">\n");
      out.write("<!-- iCheck -->\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"/admin/plugins/icheck-bootstrap/icheck-bootstrap.min.css\">\n");
      out.write("<!-- JQVMap -->\n");
      out.write("<link rel=\"stylesheet\" href=\"/admin/plugins/jqvmap/jqvmap.min.css\">\n");
      out.write("<!-- Theme style -->\n");
      out.write("<link rel=\"stylesheet\" href=\"/admin/dist/css/adminlte.min.css\">\n");
      out.write("<!-- overlayScrollbars -->\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"/admin/plugins/overlayScrollbars/css/OverlayScrollbars.min.css\">\n");
      out.write("<!-- Daterange picker -->\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"/admin/plugins/daterangepicker/daterangepicker.css\">\n");
      out.write("<!-- summernote -->\n");
      out.write("<link rel=\"stylesheet\" href=\"/admin/plugins/summernote/summernote-bs4.min.css\">\n");
      out.write("\n");
      out.write("<!-- 리액트  -->\n");
      out.write("<script src=\"https://unpkg.com/react@18/umd/react.development.js\" crossorigin></script>\n");
      out.write("<script src=\"https://unpkg.com/react-dom@18/umd/react-dom.development.js\" crossorigin></script>\n");
      out.write("<script src=\"https://unpkg.com/@babel/standalone/babel.min.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("  </head>\n");
      out.write("<body class=\"hold-transition sidebar-mini layout-fixed\">\n");
      out.write("<div class=\"wrapper\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("  <!-- Preloader -->\n");
      out.write("  <div class=\"preloader flex-column justify-content-center align-items-center\">\n");
      out.write("    <img class=\"animation__shake\" src=\"dist/img/AdminLTELogo.png\" alt=\"AdminLTELogo\" height=\"60\" width=\"60\">\n");
      out.write("  </div>");
      out.write('\n');
      out.write("\n");
      out.write("<nav class=\"main-header navbar navbar-expand navbar-white navbar-light\">\n");
      out.write("	<!-- Left navbar links -->\n");
      out.write("	<ul class=\"navbar-nav\">\n");
      out.write("		<li class=\"nav-item\"><a class=\"nav-link\" data-widget=\"pushmenu\"\n");
      out.write("			href=\"#\" role=\"button\"><i class=\"fas fa-bars\"></i></a></li>\n");
      out.write("		<li class=\"nav-item d-none d-sm-inline-block\"><a\n");
      out.write("			href=\"index3.html\" class=\"nav-link\">Home</a></li>\n");
      out.write("		<li class=\"nav-item d-none d-sm-inline-block\"><a href=\"#\"\n");
      out.write("			class=\"nav-link\">Contact</a></li>\n");
      out.write("	</ul>\n");
      out.write("\n");
      out.write("	<!-- Right navbar links -->\n");
      out.write("	<ul class=\"navbar-nav ml-auto\">\n");
      out.write("		<!-- Navbar Search -->\n");
      out.write("		<li class=\"nav-item\"><a class=\"nav-link\"\n");
      out.write("			data-widget=\"navbar-search\" href=\"#\" role=\"button\"> <i\n");
      out.write("				class=\"fas fa-search\"></i>\n");
      out.write("		</a>\n");
      out.write("			<div class=\"navbar-search-block\">\n");
      out.write("				<form class=\"form-inline\">\n");
      out.write("					<div class=\"input-group input-group-sm\">\n");
      out.write("						<input class=\"form-control form-control-navbar\" type=\"search\"\n");
      out.write("							placeholder=\"Search\" aria-label=\"Search\">\n");
      out.write("						<div class=\"input-group-append\">\n");
      out.write("							<button class=\"btn btn-navbar\" type=\"submit\">\n");
      out.write("								<i class=\"fas fa-search\"></i>\n");
      out.write("							</button>\n");
      out.write("							<button class=\"btn btn-navbar\" type=\"button\"\n");
      out.write("								data-widget=\"navbar-search\">\n");
      out.write("								<i class=\"fas fa-times\"></i>\n");
      out.write("							</button>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</form>\n");
      out.write("			</div></li>\n");
      out.write("\n");
      out.write("		<!-- Messages Dropdown Menu -->\n");
      out.write("		<li class=\"nav-item dropdown\"><a class=\"nav-link\"\n");
      out.write("			data-toggle=\"dropdown\" href=\"#\"> <i class=\"far fa-comments\"></i>\n");
      out.write("				<span class=\"badge badge-danger navbar-badge\">3</span>\n");
      out.write("		</a>\n");
      out.write("			<div class=\"dropdown-menu dropdown-menu-lg dropdown-menu-right\">\n");
      out.write("				<a href=\"#\" class=\"dropdown-item\"> <!-- Message Start -->\n");
      out.write("					<div class=\"media\">\n");
      out.write("						<img src=\"/admin/dist/img/user1-128x128.jpg\" alt=\"User Avatar\"\n");
      out.write("							class=\"img-size-50 mr-3 img-circle\">\n");
      out.write("						<div class=\"media-body\">\n");
      out.write("							<h3 class=\"dropdown-item-title\">\n");
      out.write("								Brad Diesel <span class=\"float-right text-sm text-danger\"><i\n");
      out.write("									class=\"fas fa-star\"></i></span>\n");
      out.write("							</h3>\n");
      out.write("							<p class=\"text-sm\">Call me whenever you can...</p>\n");
      out.write("							<p class=\"text-sm text-muted\">\n");
      out.write("								<i class=\"far fa-clock mr-1\"></i> 4 Hours Ago\n");
      out.write("							</p>\n");
      out.write("						</div>\n");
      out.write("					</div> <!-- Message End -->\n");
      out.write("				</a>\n");
      out.write("				<div class=\"dropdown-divider\"></div>\n");
      out.write("				<a href=\"#\" class=\"dropdown-item\"> <!-- Message Start -->\n");
      out.write("					<div class=\"media\">\n");
      out.write("						<img src=\"/admin/dist/img/user8-128x128.jpg\" alt=\"User Avatar\"\n");
      out.write("							class=\"img-size-50 img-circle mr-3\">\n");
      out.write("						<div class=\"media-body\">\n");
      out.write("							<h3 class=\"dropdown-item-title\">\n");
      out.write("								John Pierce <span class=\"float-right text-sm text-muted\"><i\n");
      out.write("									class=\"fas fa-star\"></i></span>\n");
      out.write("							</h3>\n");
      out.write("							<p class=\"text-sm\">I got your message bro</p>\n");
      out.write("							<p class=\"text-sm text-muted\">\n");
      out.write("								<i class=\"far fa-clock mr-1\"></i> 4 Hours Ago\n");
      out.write("							</p>\n");
      out.write("						</div>\n");
      out.write("					</div> <!-- Message End -->\n");
      out.write("				</a>\n");
      out.write("				<div class=\"dropdown-divider\"></div>\n");
      out.write("				<a href=\"#\" class=\"dropdown-item\"> <!-- Message Start -->\n");
      out.write("					<div class=\"media\">\n");
      out.write("						<img src=\"/admin/dist/img/user3-128x128.jpg\" alt=\"User Avatar\"\n");
      out.write("							class=\"img-size-50 img-circle mr-3\">\n");
      out.write("						<div class=\"media-body\">\n");
      out.write("							<h3 class=\"dropdown-item-title\">\n");
      out.write("								Nora Silvester <span class=\"float-right text-sm text-warning\"><i\n");
      out.write("									class=\"fas fa-star\"></i></span>\n");
      out.write("							</h3>\n");
      out.write("							<p class=\"text-sm\">The subject goes here</p>\n");
      out.write("							<p class=\"text-sm text-muted\">\n");
      out.write("								<i class=\"far fa-clock mr-1\"></i> 4 Hours Ago\n");
      out.write("							</p>\n");
      out.write("						</div>\n");
      out.write("					</div> <!-- Message End -->\n");
      out.write("				</a>\n");
      out.write("				<div class=\"dropdown-divider\"></div>\n");
      out.write("				<a href=\"#\" class=\"dropdown-item dropdown-footer\">See All\n");
      out.write("					Messages</a>\n");
      out.write("			</div></li>\n");
      out.write("		<!-- Notifications Dropdown Menu -->\n");
      out.write("		<li class=\"nav-item dropdown\"><a class=\"nav-link\"\n");
      out.write("			data-toggle=\"dropdown\" href=\"#\"> <i class=\"far fa-bell\"></i> <span\n");
      out.write("				class=\"badge badge-warning navbar-badge\">15</span>\n");
      out.write("		</a>\n");
      out.write("			<div class=\"dropdown-menu dropdown-menu-lg dropdown-menu-right\">\n");
      out.write("				<span class=\"dropdown-item dropdown-header\">15 Notifications</span>\n");
      out.write("				<div class=\"dropdown-divider\"></div>\n");
      out.write("				<a href=\"#\" class=\"dropdown-item\"> <i\n");
      out.write("					class=\"fas fa-envelope mr-2\"></i> 4 new messages <span\n");
      out.write("					class=\"float-right text-muted text-sm\">3 mins</span>\n");
      out.write("				</a>\n");
      out.write("				<div class=\"dropdown-divider\"></div>\n");
      out.write("				<a href=\"#\" class=\"dropdown-item\"> <i class=\"fas fa-users mr-2\"></i>\n");
      out.write("					8 friend requests <span class=\"float-right text-muted text-sm\">12\n");
      out.write("						hours</span>\n");
      out.write("				</a>\n");
      out.write("				<div class=\"dropdown-divider\"></div>\n");
      out.write("				<a href=\"#\" class=\"dropdown-item\"> <i class=\"fas fa-file mr-2\"></i>\n");
      out.write("					3 new reports <span class=\"float-right text-muted text-sm\">2\n");
      out.write("						days</span>\n");
      out.write("				</a>\n");
      out.write("				<div class=\"dropdown-divider\"></div>\n");
      out.write("				<a href=\"#\" class=\"dropdown-item dropdown-footer\">See All\n");
      out.write("					Notifications</a>\n");
      out.write("			</div></li>\n");
      out.write("		<li class=\"nav-item\"><a class=\"nav-link\" data-widget=\"fullscreen\"\n");
      out.write("			href=\"#\" role=\"button\"> <i class=\"fas fa-expand-arrows-alt\"></i>\n");
      out.write("		</a></li>\n");
      out.write("		<li class=\"nav-item\"><a class=\"nav-link\"\n");
      out.write("			data-widget=\"control-sidebar\" data-controlsidebar-slide=\"true\"\n");
      out.write("			href=\"#\" role=\"button\"> <i class=\"fas fa-th-large\"></i>\n");
      out.write("		</a></li>\n");
      out.write("	</ul>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("\n");
      out.write("  <!-- Main Sidebar Container -->\n");
      out.write("\n");
      out.write("<aside class=\"main-sidebar sidebar-dark-primary elevation-4\">\n");
      out.write("	<!-- Brand Logo -->\n");
      out.write("	<a href=\"index3.html\" class=\"brand-link\"> <img\n");
      out.write("		src=\"/admin/dist/img/AdminLTELogo.png\" alt=\"AdminLTE Logo\"\n");
      out.write("		class=\"brand-image img-circle elevation-3\" style=\"opacity: .8\">\n");
      out.write("		<span class=\"brand-text font-weight-light\">AdminLTE 3</span>\n");
      out.write("	</a>\n");
      out.write("\n");
      out.write("	<!-- Sidebar -->\n");
      out.write("	<div class=\"sidebar\">\n");
      out.write("		<!-- Sidebar user panel (optional) -->\n");
      out.write("		<div class=\"user-panel mt-3 pb-3 mb-3 d-flex\">\n");
      out.write("			<div class=\"image\">\n");
      out.write("				<img src=\"/admin/dist/img/user2-160x160.jpg\"\n");
      out.write("					class=\"img-circle elevation-2\" alt=\"User Image\">\n");
      out.write("			</div>\n");
      out.write("			<div class=\"info\">\n");
      out.write("\n");
      out.write("				<a href=\"#\" class=\"d-block\">");
      out.print("zino");
      out.write("</a>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("		<!-- SidebarSearch Form -->\n");
      out.write("		<div class=\"form-inline\">\n");
      out.write("			<div class=\"input-group\" data-widget=\"sidebar-search\">\n");
      out.write("				<input class=\"form-control form-control-sidebar\" type=\"search\"\n");
      out.write("					placeholder=\"Search\" aria-label=\"Search\">\n");
      out.write("				<div class=\"input-group-append\">\n");
      out.write("					<button class=\"btn btn-sidebar\">\n");
      out.write("						<i class=\"fas fa-search fa-fw\"></i>\n");
      out.write("					</button>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("		<!-- Sidebar Menu -->\n");
      out.write("		<nav class=\"mt-2\">\n");
      out.write("			<ul class=\"nav nav-pills nav-sidebar flex-column\"\n");
      out.write("				data-widget=\"treeview\" role=\"menu\" data-accordion=\"false\">\n");
      out.write("				<!-- Add icons to the links using the .nav-icon class\n");
      out.write("               with font-awesome or any other icon font library\n");
      out.write("                \n");
      out.write("               nav-item menu-open : 메뉴 열려있게..\n");
      out.write("               -->\n");
      out.write("				<li class=\"nav-item\"><a href=\"#\"\n");
      out.write("					class=\"nav-link active\"> <i\n");
      out.write("						class=\"nav-icon fas fa-tachometer-alt\"></i>\n");
      out.write("						<p>\n");
      out.write("							상점관리 <i class=\"right fas fa-angle-left\"></i>\n");
      out.write("						</p>\n");
      out.write("				</a>\n");
      out.write("					<ul class=\"nav nav-treeview\">\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index.html\"\n");
      out.write("							class=\"nav-link active\"> <i class=\"far fa-circle nav-icon\"></i>\n");
      out.write("								<p>Dashboard v1</p>\n");
      out.write("						</a></li>\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index2.html\" class=\"nav-link\">\n");
      out.write("								<i class=\"far fa-circle nav-icon\"></i>\n");
      out.write("								<p>Dashboard v2</p>\n");
      out.write("						</a></li>\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index3.html\" class=\"nav-link\">\n");
      out.write("								<i class=\"far fa-circle nav-icon\"></i>\n");
      out.write("								<p>Dashboard v3</p>\n");
      out.write("						</a></li>\n");
      out.write("					</ul></li>\n");
      out.write("					\n");
      out.write("					\n");
      out.write("				<li class=\"nav-item\"><a href=\"#\" class=\"nav-link active\">\n");
      out.write("						<i class=\"nav-icon fas fa-tachometer-alt\"></i>\n");
      out.write("						<p>\n");
      out.write("							상품관리 <i class=\"right fas fa-angle-left\"></i>\n");
      out.write("						</p>\n");
      out.write("				</a>\n");
      out.write("					<ul class=\"nav nav-treeview\">\n");
      out.write("						<li class=\"nav-item\"><a href=\"/admin/product/registform.jsp\"\n");
      out.write("							class=\"nav-link\"> <i class=\"far fa-circle nav-icon\"></i>\n");
      out.write("								<p>상품등록</p>\n");
      out.write("						</a></li>\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index2.html\" class=\"nav-link\">\n");
      out.write("								<i class=\"far fa-circle nav-icon\"></i>\n");
      out.write("								<p>일괄등록</p>\n");
      out.write("						</a></li>\n");
      out.write("						\n");
      out.write("					</ul></li>\n");
      out.write("\n");
      out.write("\n");
      out.write("				<li class=\"nav-item\"><a href=\"#\"\n");
      out.write("					class=\"nav-link active\"> <i\n");
      out.write("						class=\"nav-icon fas fa-tachometer-alt\"></i>\n");
      out.write("						<p>\n");
      out.write("							회원관리 <i class=\"right fas fa-angle-left\"></i>\n");
      out.write("						</p>\n");
      out.write("				</a>\n");
      out.write("					<ul class=\"nav nav-treeview\">\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index.html\"\n");
      out.write("							class=\"nav-link active\"> <i class=\"far fa-circle nav-icon\"></i>\n");
      out.write("								<p>Dashboard v1</p>\n");
      out.write("						</a></li>\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index2.html\" class=\"nav-link\">\n");
      out.write("								<i class=\"far fa-circle nav-icon\"></i>\n");
      out.write("								<p>Dashboard v2</p>\n");
      out.write("						</a></li>\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index3.html\" class=\"nav-link\">\n");
      out.write("								<i class=\"far fa-circle nav-icon\"></i>\n");
      out.write("								<p>Dashboard v3</p>\n");
      out.write("						</a></li>\n");
      out.write("					</ul></li>\n");
      out.write("\n");
      out.write("				<li class=\"nav-item\"><a href=\"#\"\n");
      out.write("					class=\"nav-link active\"> <i\n");
      out.write("						class=\"nav-icon fas fa-tachometer-alt\"></i>\n");
      out.write("						<p>\n");
      out.write("							주문관리 <i class=\"right fas fa-angle-left\"></i>\n");
      out.write("						</p>\n");
      out.write("				</a>\n");
      out.write("					<ul class=\"nav nav-treeview\">\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index.html\"\n");
      out.write("							class=\"nav-link active\"> <i class=\"far fa-circle nav-icon\"></i>\n");
      out.write("								<p>Dashboard v1</p>\n");
      out.write("						</a></li>\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index2.html\" class=\"nav-link\">\n");
      out.write("								<i class=\"far fa-circle nav-icon\"></i>\n");
      out.write("								<p>Dashboard v2</p>\n");
      out.write("						</a></li>\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index3.html\" class=\"nav-link\">\n");
      out.write("								<i class=\"far fa-circle nav-icon\"></i>\n");
      out.write("								<p>Dashboard v3</p>\n");
      out.write("						</a></li>\n");
      out.write("					</ul></li>\n");
      out.write("\n");
      out.write("				<li class=\"nav-item\"><a href=\"#\"\n");
      out.write("					class=\"nav-link active\"> <i\n");
      out.write("						class=\"nav-icon fas fa-tachometer-alt\"></i>\n");
      out.write("						<p>\n");
      out.write("							통계관리 <i class=\"right fas fa-angle-left\"></i>\n");
      out.write("						</p>\n");
      out.write("				</a>\n");
      out.write("					<ul class=\"nav nav-treeview\">\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index.html\"\n");
      out.write("							class=\"nav-link active\"> <i class=\"far fa-circle nav-icon\"></i>\n");
      out.write("								<p>Dashboard v1</p>\n");
      out.write("						</a></li>\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index2.html\" class=\"nav-link\">\n");
      out.write("								<i class=\"far fa-circle nav-icon\"></i>\n");
      out.write("								<p>Dashboard v2</p>\n");
      out.write("						</a></li>\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index3.html\" class=\"nav-link\">\n");
      out.write("								<i class=\"far fa-circle nav-icon\"></i>\n");
      out.write("								<p>Dashboard v3</p>\n");
      out.write("						</a></li>\n");
      out.write("					</ul></li>\n");
      out.write("\n");
      out.write("\n");
      out.write("				<li class=\"nav-item\"><a href=\"#\"\n");
      out.write("					class=\"nav-link active\"> <i\n");
      out.write("						class=\"nav-icon fas fa-tachometer-alt\"></i>\n");
      out.write("						<p>\n");
      out.write("							고객센터 <i class=\"right fas fa-angle-left\"></i>\n");
      out.write("						</p>\n");
      out.write("				</a>\n");
      out.write("					<ul class=\"nav nav-treeview\">\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index.html\"\n");
      out.write("							class=\"nav-link active\"> <i class=\"far fa-circle nav-icon\"></i>\n");
      out.write("								<p>Dashboard v1</p>\n");
      out.write("						</a></li>\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index2.html\" class=\"nav-link\">\n");
      out.write("								<i class=\"far fa-circle nav-icon\"></i>\n");
      out.write("								<p>Dashboard v2</p>\n");
      out.write("						</a></li>\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index3.html\" class=\"nav-link\">\n");
      out.write("								<i class=\"far fa-circle nav-icon\"></i>\n");
      out.write("								<p>Dashboard v3</p>\n");
      out.write("						</a></li>\n");
      out.write("					</ul></li>\n");
      out.write("\n");
      out.write("\n");
      out.write("			</ul>\n");
      out.write("		</nav>\n");
      out.write("		<!-- /.sidebar-menu -->\n");
      out.write("	</div>\n");
      out.write("	<!-- /.sidebar -->\n");
      out.write("</aside>\n");
      out.write("\n");
      out.write("\n");
      out.write("  <!-- Content Wrapper. Contains page content -->\n");
      out.write("  <div class=\"content-wrapper\">\n");
      out.write("    <!-- Content Header (Page header) -->\n");
      out.write("    <div class=\"content-header\">\n");
      out.write("      <div class=\"container-fluid\">\n");
      out.write("        <div class=\"row mb-2\">\n");
      out.write("          <div class=\"col-sm-6\">\n");
      out.write("            <h1 class=\"m-0\">Dashboard</h1>\n");
      out.write("          </div><!-- /.col -->\n");
      out.write("          <div class=\"col-sm-6\">\n");
      out.write("            <ol class=\"breadcrumb float-sm-right\">\n");
      out.write("              <li class=\"breadcrumb-item\"><a href=\"#\">Home</a></li>\n");
      out.write("              <li class=\"breadcrumb-item active\">Dashboard v1</li>\n");
      out.write("            </ol>\n");
      out.write("          </div><!-- /.col -->\n");
      out.write("        </div><!-- /.row -->\n");
      out.write("      </div><!-- /.container-fluid -->\n");
      out.write("    </div>\n");
      out.write("    <!-- /.content-header -->\n");
      out.write("    \n");
      out.write("	<!-- content -->\n");
      out.write("	<section class=\"content\">\n");
      out.write("		<div class=\"container-fluid\">\n");
      out.write("			<div class=\"col\">\n");
      out.write("				리스트 상품 나올 예정\n");
      out.write("				\n");
      out.write("				<div class=\"card\">\n");
      out.write("              <div class=\"card-header\">\n");
      out.write("                <h3 class=\"card-title\">Responsive Hover Table</h3>\n");
      out.write("\n");
      out.write("                <div class=\"card-tools\">\n");
      out.write("                  <div class=\"input-group input-group-sm\" style=\"width: 150px;\">\n");
      out.write("                    <input type=\"text\" name=\"table_search\" class=\"form-control float-right\" placeholder=\"Search\">\n");
      out.write("\n");
      out.write("                    <div class=\"input-group-append\">\n");
      out.write("                      <button type=\"submit\" class=\"btn btn-default\">\n");
      out.write("                        <i class=\"fas fa-search\"></i>\n");
      out.write("                      </button>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("              <!-- /.card-header -->\n");
      out.write("              <div class=\"card-body table-responsive p-0\">\n");
      out.write("              \n");
      out.write("              \n");
      out.write("                <table class=\"table table-hover text-nowrap\">\n");
      out.write("                  <thead>\n");
      out.write("                    <tr>\n");
      out.write("                      <th>NO</th>\n");
      out.write("                      <th>카테고리 </th>\n");
      out.write("                      <th>상품명</th>\n");
      out.write("                      <th>브랜드</th>\n");
      out.write("                      <th>가격</th>\n");
      out.write("                      <th>할인가</th>\n");
      out.write("                    </tr>\n");
      out.write("                  </thead>\n");
      out.write("                  <tbody>\n");
      out.write("				");

					int num=pm.getNum();
					int curPos=pm.getCurPos();
				
      out.write("\n");
      out.write("              	");
for(int i=1; i<=pm.getPageSize(); i++){ 
      out.write("\n");
      out.write("              	");
if(num<1)break; 
      out.write("\n");
      out.write("              	");
Product product=productList.get(curPos++); 
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                      <td>");
      out.print(num-- );
      out.write("</td>\n");
      out.write("                      <td>");
      out.print(product.getCategory().getCategory_name() );
      out.write("</td>\n");
      out.write("                      <td>");
      out.print(product.getProduct_name() );
      out.write("</td>\n");
      out.write("                      <td>");
      out.print(product.getBrand() );
      out.write("</td>\n");
      out.write("                      <td>");
      out.print(product.getPrice() );
      out.write("</td>\n");
      out.write("                      <td>");
      out.print(product.getDiscount() );
      out.write("</td>\n");
      out.write("                    </tr>\n");
      out.write("					");
} 
      out.write("\n");
      out.write("                  </tbody>                  \n");
      out.write("                </table>\n");
      out.write("              </div>\n");
      out.write("              <!-- /.card-body -->\n");
      out.write("             <div class=\"card-footer\">             \n");
      out.write("               <div class=\"dataTables_paginate paging_simple_numbers\" id=\"example2_paginate\">\n");
      out.write("               <ul class=\"pagination\">\n");
      out.write("               <li class=\"paginate_button page-item previous disabled\" id=\"example2_previous\">\n");
      out.write("               <a href=\"#\" aria-controls=\"example2\" data-dt-idx=\"0\" tabindex=\"0\" class=\"page-link\">Previous</a>\n");
      out.write("               </li>\n");
      out.write("               <li class=\"paginate_button page-item active\">\n");
      out.write("               <a href=\"#\" aria-controls=\"example2\" data-dt-idx=\"1\" tabindex=\"0\" class=\"page-link\">1</a>\n");
      out.write("               </li>\n");
      out.write("               <li class=\"paginate_button page-item \"> \n");
      out.write("               <a href=\"#\" aria-controls=\"example2\" data-dt-idx=\"2\" tabindex=\"0\" class=\"page-link\">2</a>\n");
      out.write("               </li><li class=\"paginate_button page-item \">\n");
      out.write("               <a href=\"#\" aria-controls=\"example2\" data-dt-idx=\"3\" tabindex=\"0\" class=\"page-link\">3</a>\n");
      out.write("               </li><li class=\"paginate_button page-item \"><a href=\"#\" aria-controls=\"example2\" data-dt-idx=\"4\" tabindex=\"0\" class=\"page-link\">4</a>\n");
      out.write("               </li><li class=\"paginate_button page-item \"><a href=\"#\" aria-controls=\"example2\" data-dt-idx=\"5\" tabindex=\"0\" class=\"page-link\">5</a>\n");
      out.write("               </li><li class=\"paginate_button page-item \"><a href=\"#\" aria-controls=\"example2\" data-dt-idx=\"6\" tabindex=\"0\" class=\"page-link\">6</a></li><li class=\"paginate_button page-item next\" id=\"example2_next\"><a href=\"#\" aria-controls=\"example2\" data-dt-idx=\"7\" tabindex=\"0\" class=\"page-link\">Next</a></li></ul></div>\n");
      out.write("             </div>\n");
      out.write("             \n");
      out.write("              \n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("				\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</section>\n");
      out.write("	<!-- ./content-->\n");
      out.write("\n");
      out.write("\n");
      out.write("		</div>\n");
      out.write("  <!-- /.content-wrapper -->\n");
      out.write("  \n");
      out.write("\n");
      out.write("  <footer class=\"main-footer\">\n");
      out.write("    <strong>Copyright &copy; 2014-2021 <a href=\"https://adminlte.io\">AdminLTE.io</a>.</strong>\n");
      out.write("    All rights reserved.\n");
      out.write("    <div class=\"float-right d-none d-sm-inline-block\">\n");
      out.write("      <b>Version</b> 3.2.0\n");
      out.write("    </div>\n");
      out.write("  </footer>");
      out.write("\n");
      out.write("\n");
      out.write("  <!-- Control Sidebar -->\n");
      out.write("\n");
      out.write("  <aside class=\"control-sidebar control-sidebar-dark\">\n");
      out.write("    <!-- Control sidebar content goes here -->\n");
      out.write("  </aside>");
      out.write("\n");
      out.write("\n");
      out.write("  <!-- /.control-sidebar -->\n");
      out.write("</div>\n");
      out.write("<!-- ./wrapper -->\n");
      out.write("\n");
      out.write("\n");
      out.write("	<!-- jQuery -->\n");
      out.write("	<script src=\"/admin/plugins/jquery/jquery.min.js\"></script>\n");
      out.write("	<!-- jQuery UI 1.11.4 -->\n");
      out.write("	<script src=\"/admin/plugins/jquery-ui/jquery-ui.min.js\"></script>\n");
      out.write("	<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->\n");
      out.write("	<script>\n");
      out.write("		//$.widget.bridge('uibutton', $.ui.button)\n");
      out.write("	</script>\n");
      out.write("	<!-- Bootstrap 4 -->\n");
      out.write("	<script src=\"/admin/plugins/bootstrap/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("	<!-- ChartJS -->\n");
      out.write("	<script src=\"/admin/plugins/chart.js/Chart.min.js\"></script>\n");
      out.write("	<!-- Sparkline -->\n");
      out.write("	<script src=\"/admin/plugins/sparklines/sparkline.js\"></script>\n");
      out.write("	<!-- JQVMap -->\n");
      out.write("	<script src=\"/admin/plugins/jqvmap/jquery.vmap.min.js\"></script>\n");
      out.write("	<script src=\"/admin/plugins/jqvmap/maps/jquery.vmap.usa.js\"></script>\n");
      out.write("	<!-- jQuery Knob Chart -->\n");
      out.write("	<script src=\"/admin/plugins/jquery-knob/jquery.knob.min.js\"></script>\n");
      out.write("	<!-- daterangepicker -->\n");
      out.write("	<script src=\"/admin/plugins/moment/moment.min.js\"></script>\n");
      out.write("	<script src=\"/admin/plugins/daterangepicker/daterangepicker.js\"></script>\n");
      out.write("	<!-- Tempusdominus Bootstrap 4 -->\n");
      out.write("	<script\n");
      out.write("		src=\"/admin/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js\"></script>\n");
      out.write("	<!-- Summernote -->\n");
      out.write("	<script src=\"/admin/plugins/summernote/summernote-bs4.min.js\"></script>\n");
      out.write("	<!-- overlayScrollbars -->\n");
      out.write("	<script\n");
      out.write("		src=\"/admin/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js\"></script>\n");
      out.write("	<!-- AdminLTE App -->\n");
      out.write("	<script src=\"/admin/dist/js/adminlte.js\"></script>\n");
      out.write("	\n");
      out.write("	<!-- AdminLTE for demo purposes -->\n");
      out.write("	<!-- <script src=\"/admin/dist/js/demo.js\"></script> -->\n");
      out.write("	\n");
      out.write("	<!-- AdminLTE dashboard demo (This is only for demo purposes) -->\n");
      out.write("	<!-- <script src=\"/admin/dist/js/pages/dashboard.js\"></script> -->\n");
      out.write("	");
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
