/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-01-26 07:40:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class registform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/admin/inc/sidebar_right.jsp", Long.valueOf(1674045568000L));
    _jspx_dependants.put("/admin/inc/footer_link.jsp", Long.valueOf(1674123080000L));
    _jspx_dependants.put("/admin/inc/footer.jsp", Long.valueOf(1674043732000L));
    _jspx_dependants.put("/admin/inc/header_link.jsp", Long.valueOf(1674212252000L));
    _jspx_dependants.put("/admin/inc/preloader.jsp", Long.valueOf(1674044051000L));
    _jspx_dependants.put("/admin/inc/sidebar_left.jsp", Long.valueOf(1674044524000L));
    _jspx_dependants.put("/admin/inc/navbar.jsp", Long.valueOf(1674045009000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

	String[] sizeList={"XS","S","M","L","XL","XXL"};
	String[] colorList={"베이지","네이비","브라운","블랙"};

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"utf-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("  <title>상품 등록 </title>\n");
      out.write("\n");
      out.write("<!-- Google Font: Source Sans Pro -->\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback\">\n");
      out.write("<!-- Font Awesome -->\n");
      out.write("<link rel=\"stylesheet\" href=\"/admin/plugins/fontawesome-free/css/all.min.css\">\n");
      out.write("<!-- Ionicons -->\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css\">\n");
      out.write("<!-- Tempusdominus Bootstrap 4 -->\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"/admin/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css\">\n");
      out.write("<!-- iCheck -->\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"/admin/plugins/icheck-bootstrap/icheck-bootstrap.min.css\">\n");
      out.write("<!-- JQVMap -->\n");
      out.write("<link rel=\"stylesheet\" href=\"/admin/plugins/jqvmap/jqvmap.min.css\">\n");
      out.write("<!-- Theme style -->\n");
      out.write("<link rel=\"stylesheet\" href=\"/admin/dist/css/adminlte.min.css\">\n");
      out.write("<!-- overlayScrollbars -->\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"/admin/plugins/overlayScrollbars/css/OverlayScrollbars.min.css\">\n");
      out.write("<!-- Daterange picker -->\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"/admin/plugins/daterangepicker/daterangepicker.css\">\n");
      out.write("<!-- summernote -->\n");
      out.write("<link rel=\"stylesheet\" href=\"/admin/plugins/summernote/summernote-bs4.min.css\">\n");
      out.write("\n");
      out.write("<!-- 리액트  -->\n");
      out.write("<script src=\"https://unpkg.com/react@18/umd/react.development.js\" crossorigin></script>\n");
      out.write("<script src=\"https://unpkg.com/react-dom@18/umd/react-dom.development.js\" crossorigin></script>\n");
      out.write("<script src=\"https://unpkg.com/@babel/standalone/babel.min.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("  </head>\n");
      out.write("<body class=\"hold-transition sidebar-mini layout-fixed\">\n");
      out.write("<div class=\"wrapper\">\n");
      out.write("\n");
      out.write("\n");
      out.write("  <!-- Preloader -->\n");
      out.write("  <div class=\"preloader flex-column justify-content-center align-items-center\">\n");
      out.write("    <img class=\"animation__shake\" src=\"dist/img/AdminLTELogo.png\" alt=\"AdminLTELogo\" height=\"60\" width=\"60\">\n");
      out.write("  </div>");
      out.write('\n');
      out.write("\n");
      out.write("<nav class=\"main-header navbar navbar-expand navbar-white navbar-light\">\n");
      out.write("	<!-- Left navbar links -->\n");
      out.write("	<ul class=\"navbar-nav\">\n");
      out.write("		<li class=\"nav-item\"><a class=\"nav-link\" data-widget=\"pushmenu\"\n");
      out.write("			href=\"#\" role=\"button\"><i class=\"fas fa-bars\"></i></a></li>\n");
      out.write("		<li class=\"nav-item d-none d-sm-inline-block\"><a\n");
      out.write("			href=\"index3.html\" class=\"nav-link\">Home</a></li>\n");
      out.write("		<li class=\"nav-item d-none d-sm-inline-block\"><a href=\"#\"\n");
      out.write("			class=\"nav-link\">Contact</a></li>\n");
      out.write("	</ul>\n");
      out.write("\n");
      out.write("	<!-- Right navbar links -->\n");
      out.write("	<ul class=\"navbar-nav ml-auto\">\n");
      out.write("		<!-- Navbar Search -->\n");
      out.write("		<li class=\"nav-item\"><a class=\"nav-link\"\n");
      out.write("			data-widget=\"navbar-search\" href=\"#\" role=\"button\"> <i\n");
      out.write("				class=\"fas fa-search\"></i>\n");
      out.write("		</a>\n");
      out.write("			<div class=\"navbar-search-block\">\n");
      out.write("				<form class=\"form-inline\">\n");
      out.write("					<div class=\"input-group input-group-sm\">\n");
      out.write("						<input class=\"form-control form-control-navbar\" type=\"search\"\n");
      out.write("							placeholder=\"Search\" aria-label=\"Search\">\n");
      out.write("						<div class=\"input-group-append\">\n");
      out.write("							<button class=\"btn btn-navbar\" type=\"submit\">\n");
      out.write("								<i class=\"fas fa-search\"></i>\n");
      out.write("							</button>\n");
      out.write("							<button class=\"btn btn-navbar\" type=\"button\"\n");
      out.write("								data-widget=\"navbar-search\">\n");
      out.write("								<i class=\"fas fa-times\"></i>\n");
      out.write("							</button>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</form>\n");
      out.write("			</div></li>\n");
      out.write("\n");
      out.write("		<!-- Messages Dropdown Menu -->\n");
      out.write("		<li class=\"nav-item dropdown\"><a class=\"nav-link\"\n");
      out.write("			data-toggle=\"dropdown\" href=\"#\"> <i class=\"far fa-comments\"></i>\n");
      out.write("				<span class=\"badge badge-danger navbar-badge\">3</span>\n");
      out.write("		</a>\n");
      out.write("			<div class=\"dropdown-menu dropdown-menu-lg dropdown-menu-right\">\n");
      out.write("				<a href=\"#\" class=\"dropdown-item\"> <!-- Message Start -->\n");
      out.write("					<div class=\"media\">\n");
      out.write("						<img src=\"/admin/dist/img/user1-128x128.jpg\" alt=\"User Avatar\"\n");
      out.write("							class=\"img-size-50 mr-3 img-circle\">\n");
      out.write("						<div class=\"media-body\">\n");
      out.write("							<h3 class=\"dropdown-item-title\">\n");
      out.write("								Brad Diesel <span class=\"float-right text-sm text-danger\"><i\n");
      out.write("									class=\"fas fa-star\"></i></span>\n");
      out.write("							</h3>\n");
      out.write("							<p class=\"text-sm\">Call me whenever you can...</p>\n");
      out.write("							<p class=\"text-sm text-muted\">\n");
      out.write("								<i class=\"far fa-clock mr-1\"></i> 4 Hours Ago\n");
      out.write("							</p>\n");
      out.write("						</div>\n");
      out.write("					</div> <!-- Message End -->\n");
      out.write("				</a>\n");
      out.write("				<div class=\"dropdown-divider\"></div>\n");
      out.write("				<a href=\"#\" class=\"dropdown-item\"> <!-- Message Start -->\n");
      out.write("					<div class=\"media\">\n");
      out.write("						<img src=\"/admin/dist/img/user8-128x128.jpg\" alt=\"User Avatar\"\n");
      out.write("							class=\"img-size-50 img-circle mr-3\">\n");
      out.write("						<div class=\"media-body\">\n");
      out.write("							<h3 class=\"dropdown-item-title\">\n");
      out.write("								John Pierce <span class=\"float-right text-sm text-muted\"><i\n");
      out.write("									class=\"fas fa-star\"></i></span>\n");
      out.write("							</h3>\n");
      out.write("							<p class=\"text-sm\">I got your message bro</p>\n");
      out.write("							<p class=\"text-sm text-muted\">\n");
      out.write("								<i class=\"far fa-clock mr-1\"></i> 4 Hours Ago\n");
      out.write("							</p>\n");
      out.write("						</div>\n");
      out.write("					</div> <!-- Message End -->\n");
      out.write("				</a>\n");
      out.write("				<div class=\"dropdown-divider\"></div>\n");
      out.write("				<a href=\"#\" class=\"dropdown-item\"> <!-- Message Start -->\n");
      out.write("					<div class=\"media\">\n");
      out.write("						<img src=\"/admin/dist/img/user3-128x128.jpg\" alt=\"User Avatar\"\n");
      out.write("							class=\"img-size-50 img-circle mr-3\">\n");
      out.write("						<div class=\"media-body\">\n");
      out.write("							<h3 class=\"dropdown-item-title\">\n");
      out.write("								Nora Silvester <span class=\"float-right text-sm text-warning\"><i\n");
      out.write("									class=\"fas fa-star\"></i></span>\n");
      out.write("							</h3>\n");
      out.write("							<p class=\"text-sm\">The subject goes here</p>\n");
      out.write("							<p class=\"text-sm text-muted\">\n");
      out.write("								<i class=\"far fa-clock mr-1\"></i> 4 Hours Ago\n");
      out.write("							</p>\n");
      out.write("						</div>\n");
      out.write("					</div> <!-- Message End -->\n");
      out.write("				</a>\n");
      out.write("				<div class=\"dropdown-divider\"></div>\n");
      out.write("				<a href=\"#\" class=\"dropdown-item dropdown-footer\">See All\n");
      out.write("					Messages</a>\n");
      out.write("			</div></li>\n");
      out.write("		<!-- Notifications Dropdown Menu -->\n");
      out.write("		<li class=\"nav-item dropdown\"><a class=\"nav-link\"\n");
      out.write("			data-toggle=\"dropdown\" href=\"#\"> <i class=\"far fa-bell\"></i> <span\n");
      out.write("				class=\"badge badge-warning navbar-badge\">15</span>\n");
      out.write("		</a>\n");
      out.write("			<div class=\"dropdown-menu dropdown-menu-lg dropdown-menu-right\">\n");
      out.write("				<span class=\"dropdown-item dropdown-header\">15 Notifications</span>\n");
      out.write("				<div class=\"dropdown-divider\"></div>\n");
      out.write("				<a href=\"#\" class=\"dropdown-item\"> <i\n");
      out.write("					class=\"fas fa-envelope mr-2\"></i> 4 new messages <span\n");
      out.write("					class=\"float-right text-muted text-sm\">3 mins</span>\n");
      out.write("				</a>\n");
      out.write("				<div class=\"dropdown-divider\"></div>\n");
      out.write("				<a href=\"#\" class=\"dropdown-item\"> <i class=\"fas fa-users mr-2\"></i>\n");
      out.write("					8 friend requests <span class=\"float-right text-muted text-sm\">12\n");
      out.write("						hours</span>\n");
      out.write("				</a>\n");
      out.write("				<div class=\"dropdown-divider\"></div>\n");
      out.write("				<a href=\"#\" class=\"dropdown-item\"> <i class=\"fas fa-file mr-2\"></i>\n");
      out.write("					3 new reports <span class=\"float-right text-muted text-sm\">2\n");
      out.write("						days</span>\n");
      out.write("				</a>\n");
      out.write("				<div class=\"dropdown-divider\"></div>\n");
      out.write("				<a href=\"#\" class=\"dropdown-item dropdown-footer\">See All\n");
      out.write("					Notifications</a>\n");
      out.write("			</div></li>\n");
      out.write("		<li class=\"nav-item\"><a class=\"nav-link\" data-widget=\"fullscreen\"\n");
      out.write("			href=\"#\" role=\"button\"> <i class=\"fas fa-expand-arrows-alt\"></i>\n");
      out.write("		</a></li>\n");
      out.write("		<li class=\"nav-item\"><a class=\"nav-link\"\n");
      out.write("			data-widget=\"control-sidebar\" data-controlsidebar-slide=\"true\"\n");
      out.write("			href=\"#\" role=\"button\"> <i class=\"fas fa-th-large\"></i>\n");
      out.write("		</a></li>\n");
      out.write("	</ul>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("\n");
      out.write("  <!-- Main Sidebar Container -->\n");
      out.write("\n");
      out.write("<aside class=\"main-sidebar sidebar-dark-primary elevation-4\">\n");
      out.write("	<!-- Brand Logo -->\n");
      out.write("	<a href=\"index3.html\" class=\"brand-link\"> <img\n");
      out.write("		src=\"/admin/dist/img/AdminLTELogo.png\" alt=\"AdminLTE Logo\"\n");
      out.write("		class=\"brand-image img-circle elevation-3\" style=\"opacity: .8\">\n");
      out.write("		<span class=\"brand-text font-weight-light\">AdminLTE 3</span>\n");
      out.write("	</a>\n");
      out.write("\n");
      out.write("	<!-- Sidebar -->\n");
      out.write("	<div class=\"sidebar\">\n");
      out.write("		<!-- Sidebar user panel (optional) -->\n");
      out.write("		<div class=\"user-panel mt-3 pb-3 mb-3 d-flex\">\n");
      out.write("			<div class=\"image\">\n");
      out.write("				<img src=\"/admin/dist/img/user2-160x160.jpg\"\n");
      out.write("					class=\"img-circle elevation-2\" alt=\"User Image\">\n");
      out.write("			</div>\n");
      out.write("			<div class=\"info\">\n");
      out.write("\n");
      out.write("				<a href=\"#\" class=\"d-block\">");
      out.print("zino");
      out.write("</a>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("		<!-- SidebarSearch Form -->\n");
      out.write("		<div class=\"form-inline\">\n");
      out.write("			<div class=\"input-group\" data-widget=\"sidebar-search\">\n");
      out.write("				<input class=\"form-control form-control-sidebar\" type=\"search\"\n");
      out.write("					placeholder=\"Search\" aria-label=\"Search\">\n");
      out.write("				<div class=\"input-group-append\">\n");
      out.write("					<button class=\"btn btn-sidebar\">\n");
      out.write("						<i class=\"fas fa-search fa-fw\"></i>\n");
      out.write("					</button>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("		<!-- Sidebar Menu -->\n");
      out.write("		<nav class=\"mt-2\">\n");
      out.write("			<ul class=\"nav nav-pills nav-sidebar flex-column\"\n");
      out.write("				data-widget=\"treeview\" role=\"menu\" data-accordion=\"false\">\n");
      out.write("				<!-- Add icons to the links using the .nav-icon class\n");
      out.write("               with font-awesome or any other icon font library\n");
      out.write("                \n");
      out.write("               nav-item menu-open : 메뉴 열려있게..\n");
      out.write("               -->\n");
      out.write("				<li class=\"nav-item\"><a href=\"#\"\n");
      out.write("					class=\"nav-link active\"> <i\n");
      out.write("						class=\"nav-icon fas fa-tachometer-alt\"></i>\n");
      out.write("						<p>\n");
      out.write("							상점관리 <i class=\"right fas fa-angle-left\"></i>\n");
      out.write("						</p>\n");
      out.write("				</a>\n");
      out.write("					<ul class=\"nav nav-treeview\">\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index.html\"\n");
      out.write("							class=\"nav-link active\"> <i class=\"far fa-circle nav-icon\"></i>\n");
      out.write("								<p>Dashboard v1</p>\n");
      out.write("						</a></li>\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index2.html\" class=\"nav-link\">\n");
      out.write("								<i class=\"far fa-circle nav-icon\"></i>\n");
      out.write("								<p>Dashboard v2</p>\n");
      out.write("						</a></li>\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index3.html\" class=\"nav-link\">\n");
      out.write("								<i class=\"far fa-circle nav-icon\"></i>\n");
      out.write("								<p>Dashboard v3</p>\n");
      out.write("						</a></li>\n");
      out.write("					</ul></li>\n");
      out.write("					\n");
      out.write("					\n");
      out.write("				<li class=\"nav-item\"><a href=\"#\" class=\"nav-link active\">\n");
      out.write("						<i class=\"nav-icon fas fa-tachometer-alt\"></i>\n");
      out.write("						<p>\n");
      out.write("							상품관리 <i class=\"right fas fa-angle-left\"></i>\n");
      out.write("						</p>\n");
      out.write("				</a>\n");
      out.write("					<ul class=\"nav nav-treeview\">\n");
      out.write("						<li class=\"nav-item\"><a href=\"/admin/product/registform.jsp\"\n");
      out.write("							class=\"nav-link\"> <i class=\"far fa-circle nav-icon\"></i>\n");
      out.write("								<p>상품등록</p>\n");
      out.write("						</a></li>\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index2.html\" class=\"nav-link\">\n");
      out.write("								<i class=\"far fa-circle nav-icon\"></i>\n");
      out.write("								<p>일괄등록</p>\n");
      out.write("						</a></li>\n");
      out.write("						\n");
      out.write("					</ul></li>\n");
      out.write("\n");
      out.write("\n");
      out.write("				<li class=\"nav-item\"><a href=\"#\"\n");
      out.write("					class=\"nav-link active\"> <i\n");
      out.write("						class=\"nav-icon fas fa-tachometer-alt\"></i>\n");
      out.write("						<p>\n");
      out.write("							회원관리 <i class=\"right fas fa-angle-left\"></i>\n");
      out.write("						</p>\n");
      out.write("				</a>\n");
      out.write("					<ul class=\"nav nav-treeview\">\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index.html\"\n");
      out.write("							class=\"nav-link active\"> <i class=\"far fa-circle nav-icon\"></i>\n");
      out.write("								<p>Dashboard v1</p>\n");
      out.write("						</a></li>\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index2.html\" class=\"nav-link\">\n");
      out.write("								<i class=\"far fa-circle nav-icon\"></i>\n");
      out.write("								<p>Dashboard v2</p>\n");
      out.write("						</a></li>\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index3.html\" class=\"nav-link\">\n");
      out.write("								<i class=\"far fa-circle nav-icon\"></i>\n");
      out.write("								<p>Dashboard v3</p>\n");
      out.write("						</a></li>\n");
      out.write("					</ul></li>\n");
      out.write("\n");
      out.write("				<li class=\"nav-item\"><a href=\"#\"\n");
      out.write("					class=\"nav-link active\"> <i\n");
      out.write("						class=\"nav-icon fas fa-tachometer-alt\"></i>\n");
      out.write("						<p>\n");
      out.write("							주문관리 <i class=\"right fas fa-angle-left\"></i>\n");
      out.write("						</p>\n");
      out.write("				</a>\n");
      out.write("					<ul class=\"nav nav-treeview\">\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index.html\"\n");
      out.write("							class=\"nav-link active\"> <i class=\"far fa-circle nav-icon\"></i>\n");
      out.write("								<p>Dashboard v1</p>\n");
      out.write("						</a></li>\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index2.html\" class=\"nav-link\">\n");
      out.write("								<i class=\"far fa-circle nav-icon\"></i>\n");
      out.write("								<p>Dashboard v2</p>\n");
      out.write("						</a></li>\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index3.html\" class=\"nav-link\">\n");
      out.write("								<i class=\"far fa-circle nav-icon\"></i>\n");
      out.write("								<p>Dashboard v3</p>\n");
      out.write("						</a></li>\n");
      out.write("					</ul></li>\n");
      out.write("\n");
      out.write("				<li class=\"nav-item\"><a href=\"#\"\n");
      out.write("					class=\"nav-link active\"> <i\n");
      out.write("						class=\"nav-icon fas fa-tachometer-alt\"></i>\n");
      out.write("						<p>\n");
      out.write("							통계관리 <i class=\"right fas fa-angle-left\"></i>\n");
      out.write("						</p>\n");
      out.write("				</a>\n");
      out.write("					<ul class=\"nav nav-treeview\">\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index.html\"\n");
      out.write("							class=\"nav-link active\"> <i class=\"far fa-circle nav-icon\"></i>\n");
      out.write("								<p>Dashboard v1</p>\n");
      out.write("						</a></li>\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index2.html\" class=\"nav-link\">\n");
      out.write("								<i class=\"far fa-circle nav-icon\"></i>\n");
      out.write("								<p>Dashboard v2</p>\n");
      out.write("						</a></li>\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index3.html\" class=\"nav-link\">\n");
      out.write("								<i class=\"far fa-circle nav-icon\"></i>\n");
      out.write("								<p>Dashboard v3</p>\n");
      out.write("						</a></li>\n");
      out.write("					</ul></li>\n");
      out.write("\n");
      out.write("\n");
      out.write("				<li class=\"nav-item\"><a href=\"#\"\n");
      out.write("					class=\"nav-link active\"> <i\n");
      out.write("						class=\"nav-icon fas fa-tachometer-alt\"></i>\n");
      out.write("						<p>\n");
      out.write("							고객센터 <i class=\"right fas fa-angle-left\"></i>\n");
      out.write("						</p>\n");
      out.write("				</a>\n");
      out.write("					<ul class=\"nav nav-treeview\">\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index.html\"\n");
      out.write("							class=\"nav-link active\"> <i class=\"far fa-circle nav-icon\"></i>\n");
      out.write("								<p>Dashboard v1</p>\n");
      out.write("						</a></li>\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index2.html\" class=\"nav-link\">\n");
      out.write("								<i class=\"far fa-circle nav-icon\"></i>\n");
      out.write("								<p>Dashboard v2</p>\n");
      out.write("						</a></li>\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index3.html\" class=\"nav-link\">\n");
      out.write("								<i class=\"far fa-circle nav-icon\"></i>\n");
      out.write("								<p>Dashboard v3</p>\n");
      out.write("						</a></li>\n");
      out.write("					</ul></li>\n");
      out.write("\n");
      out.write("\n");
      out.write("			</ul>\n");
      out.write("		</nav>\n");
      out.write("		<!-- /.sidebar-menu -->\n");
      out.write("	</div>\n");
      out.write("	<!-- /.sidebar -->\n");
      out.write("</aside>\n");
      out.write("\n");
      out.write("\n");
      out.write("  <!-- Content Wrapper. Contains page content -->\n");
      out.write("  <div class=\"content-wrapper\">\n");
      out.write("    <!-- Content Header (Page header) -->\n");
      out.write("    <div class=\"content-header\">\n");
      out.write("      <div class=\"container-fluid\">\n");
      out.write("        <div class=\"row mb-2\">\n");
      out.write("          <div class=\"col-sm-6\">\n");
      out.write("            <h1 class=\"m-0\">Dashboard</h1>\n");
      out.write("          </div><!-- /.col -->\n");
      out.write("          <div class=\"col-sm-6\">\n");
      out.write("            <ol class=\"breadcrumb float-sm-right\">\n");
      out.write("              <li class=\"breadcrumb-item\"><a href=\"#\">Home</a></li>\n");
      out.write("              <li class=\"breadcrumb-item active\">Dashboard v1</li>\n");
      out.write("            </ol>\n");
      out.write("          </div><!-- /.col -->\n");
      out.write("        </div><!-- /.row -->\n");
      out.write("      </div><!-- /.container-fluid -->\n");
      out.write("    </div>\n");
      out.write("    <!-- /.content-header -->\n");
      out.write("    \n");
      out.write("	<!-- content -->\n");
      out.write("	<section class=\"content\">\n");
      out.write("		<div class=\"container-fluid\">\n");
      out.write("			<div class=\"col\">\n");
      out.write("\n");
      out.write("				<div class=\"form-group\">\n");
      out.write("					<select class=\"form-control\" id=\"category_idx\"></select>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"form-group\">\n");
      out.write("					<input type=\"text\" class=\"form-control\" id=\"product_name\" placeholder=\"상품명\">\n");
      out.write("				</div>\n");
      out.write("				<div class=\"form-group\">\n");
      out.write("					<input type=\"text\" class=\"form-control\" id=\"brand\" placeholder=\"브랜드\">\n");
      out.write("				</div>\n");
      out.write("				<div class=\"form-group\">\n");
      out.write("					<input type=\"number\" class=\"form-control\" id=\"price\" placeholder=\"가격\">\n");
      out.write("				</div>\n");
      out.write("				<div class=\"form-group\">\n");
      out.write("					<input type=\"text\" class=\"form-control\" id=\"discount\" placeholder=\"할인가\">\n");
      out.write("				</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("				<div class=\"form-group\">\n");
      out.write("					");
for(int i=0; i<sizeList.length; i++){ 
      out.write("\n");
      out.write("					<div class=\"icheck-primary d-inline\">\n");
      out.write("						<input type=\"checkbox\" id=\"size");
      out.print(i );
      out.write("\" name=\"size\" value=\"");
      out.print(sizeList[i]);
      out.write("\">\n");
      out.write("						<label for=\"size");
      out.print(i);
      out.write('"');
      out.write('>');
      out.print(sizeList[i]);
      out.write("</label>\n");
      out.write("					</div>\n");
      out.write("					");
} 
      out.write("\n");
      out.write("				</div>\n");
      out.write("\n");
      out.write("				<div class=\"form-group\">\n");
      out.write("					");
for(int i=0; i<colorList.length; i++){ 
      out.write("\n");
      out.write("					<div class=\"icheck-primary d-inline\">\n");
      out.write("						<input type=\"checkbox\" id=\"color");
      out.print(i );
      out.write("\" name=\"color\" value=\"");
      out.print(colorList[i]);
      out.write("\">\n");
      out.write("						<label for=\"color");
      out.print(i);
      out.write('"');
      out.write('>');
      out.print(colorList[i]);
      out.write("</label>\n");
      out.write("					</div>\n");
      out.write("					");
} 
      out.write("\n");
      out.write("				</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("				<div class=\"form-group\">\n");
      out.write("                  <textarea id=\"detail\" class=\"form-control\" ></textarea>\n");
      out.write("            	</div>\n");
      out.write("\n");
      out.write("				<div class=\"form-group\">\n");
      out.write("					<input type=\"file\" id=\"file\" multiple>\n");
      out.write("				</div>\n");
      out.write("						\n");
      out.write("				<!-- 미리보기 이미지 -->\n");
      out.write("				<div class=\"row form-group\" id=\"preview\">\n");
      out.write("					이미지 나올곳\n");
      out.write("				</div>\n");
      out.write("\n");
      out.write("				<div class=\"form-group\">\n");
      out.write("						<button type=\"button\" class=\"btn btn-primary\" id=\"bt_regist\">등록</button>\n");
      out.write("						<button type=\"button\" class=\"btn btn-primary\" id=\"bt_list\">목록</button>\n");
      out.write("				</div>\n");
      out.write("\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</section>\n");
      out.write("	<!-- ./content-->\n");
      out.write("\n");
      out.write("\n");
      out.write("		</div>\n");
      out.write("  <!-- /.content-wrapper -->\n");
      out.write("  \n");
      out.write("\n");
      out.write("  <footer class=\"main-footer\">\n");
      out.write("    <strong>Copyright &copy; 2014-2021 <a href=\"https://adminlte.io\">AdminLTE.io</a>.</strong>\n");
      out.write("    All rights reserved.\n");
      out.write("    <div class=\"float-right d-none d-sm-inline-block\">\n");
      out.write("      <b>Version</b> 3.2.0\n");
      out.write("    </div>\n");
      out.write("  </footer>");
      out.write("\n");
      out.write("\n");
      out.write("  <!-- Control Sidebar -->\n");
      out.write("\n");
      out.write("  <aside class=\"control-sidebar control-sidebar-dark\">\n");
      out.write("    <!-- Control sidebar content goes here -->\n");
      out.write("  </aside>");
      out.write("\n");
      out.write("\n");
      out.write("  <!-- /.control-sidebar -->\n");
      out.write("</div>\n");
      out.write("<!-- ./wrapper -->\n");
      out.write("\n");
      out.write("\n");
      out.write("	<!-- jQuery -->\n");
      out.write("	<script src=\"/admin/plugins/jquery/jquery.min.js\"></script>\n");
      out.write("	<!-- jQuery UI 1.11.4 -->\n");
      out.write("	<script src=\"/admin/plugins/jquery-ui/jquery-ui.min.js\"></script>\n");
      out.write("	<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->\n");
      out.write("	<script>\n");
      out.write("		//$.widget.bridge('uibutton', $.ui.button)\n");
      out.write("	</script>\n");
      out.write("	<!-- Bootstrap 4 -->\n");
      out.write("	<script src=\"/admin/plugins/bootstrap/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("	<!-- ChartJS -->\n");
      out.write("	<script src=\"/admin/plugins/chart.js/Chart.min.js\"></script>\n");
      out.write("	<!-- Sparkline -->\n");
      out.write("	<script src=\"/admin/plugins/sparklines/sparkline.js\"></script>\n");
      out.write("	<!-- JQVMap -->\n");
      out.write("	<script src=\"/admin/plugins/jqvmap/jquery.vmap.min.js\"></script>\n");
      out.write("	<script src=\"/admin/plugins/jqvmap/maps/jquery.vmap.usa.js\"></script>\n");
      out.write("	<!-- jQuery Knob Chart -->\n");
      out.write("	<script src=\"/admin/plugins/jquery-knob/jquery.knob.min.js\"></script>\n");
      out.write("	<!-- daterangepicker -->\n");
      out.write("	<script src=\"/admin/plugins/moment/moment.min.js\"></script>\n");
      out.write("	<script src=\"/admin/plugins/daterangepicker/daterangepicker.js\"></script>\n");
      out.write("	<!-- Tempusdominus Bootstrap 4 -->\n");
      out.write("	<script\n");
      out.write("		src=\"/admin/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js\"></script>\n");
      out.write("	<!-- Summernote -->\n");
      out.write("	<script src=\"/admin/plugins/summernote/summernote-bs4.min.js\"></script>\n");
      out.write("	<!-- overlayScrollbars -->\n");
      out.write("	<script\n");
      out.write("		src=\"/admin/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js\"></script>\n");
      out.write("	<!-- AdminLTE App -->\n");
      out.write("	<script src=\"/admin/dist/js/adminlte.js\"></script>\n");
      out.write("	\n");
      out.write("	<!-- AdminLTE for demo purposes -->\n");
      out.write("	<!-- <script src=\"/admin/dist/js/demo.js\"></script> -->\n");
      out.write("	\n");
      out.write("	<!-- AdminLTE dashboard demo (This is only for demo purposes) -->\n");
      out.write("	<!-- <script src=\"/admin/dist/js/pages/dashboard.js\"></script> -->\n");
      out.write("	");
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("	function regist(){\n");
      out.write("		let formData = new FormData();\n");
      out.write("		\n");
      out.write("		formData.append(\"category_idx\", $(\"#category_idx\").val());\n");
      out.write("		formData.append(\"product_name\", $(\"#product_name\").val());\n");
      out.write("		formData.append(\"brand\", $(\"#brand\").val());\n");
      out.write("		formData.append(\"price\", $(\"#price\").val());\n");
      out.write("		formData.append(\"discount\", $(\"#discount\").val());\n");
      out.write("		\n");
      out.write("		// 체크박스 배열화해서 보내기!\n");
      out.write("		let sizeCheckArray=[];\n");
      out.write("		for(let i=0; i<$(\"input[name='size']\").length; i++){\n");
      out.write("			if($($(\"input[name='size']\")[i]).is(\":checked\")){\n");
      out.write("				sizeCheckArray.push($($(\"input[name='size']\")[i]).val());\n");
      out.write("			}\n");
      out.write("		}\n");
      out.write("		// 모아 놓은 배열 보내기! 파라미터 이름은 배열로 지정 !\n");
      out.write("		formData.append(\"size[]\", sizeCheckArray);\n");
      out.write("		\n");
      out.write("		// jQuery \n");
      out.write("		let colorCheckArray=[];\n");
      out.write("		$.each($(\"input[name='color']:checked\"), function(){\n");
      out.write("			colorCheckArray.push($(this).val());\n");
      out.write("		});\n");
      out.write("		formData.append(\"color[]\", colorCheckArray);\n");
      out.write("		\n");
      out.write("		formData.append(\"detail\", $(\"#detail\").val());\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		console.log(fileList);\n");
      out.write("		for(let i=0;i<fileList.length;i++){\n");
      out.write("			let file = fileList[i];\n");
      out.write("			formData.append(\"file\", file);\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		$.ajax({\n");
      out.write("			url:\"/admin/product/regist2.jsp\",\n");
      out.write("			type: \"POST\",\n");
      out.write("			\n");
      out.write("			// 바이너리 파일 보낼 때 세팅!\n");
      out.write("			processData:false,\n");
      out.write("			contentType:false,\n");
      out.write("			data:formData,\n");
      out.write("			\n");
      out.write("			success:function(result, status, xhr){\n");
      out.write("				console.log(\"응답 \"+result);\n");
      out.write("			}\n");
      out.write("		});\n");
      out.write("	}\n");
      out.write("</script>\n");
      out.write("<script type=\"text/babel\">\n");
      out.write("	let tag=[];	\n");
      out.write("	let previewRoot;\n");
      out.write("	let fileList=[];\n");
      out.write("	let oriFiles=[];\n");
      out.write("\n");
      out.write("	function ImgBox(props){\n");
      out.write("		return(\n");
      out.write("			<div className=\"col-sm-2 border\">\n");
      out.write("				<div>\n");
      out.write("					<a href=\"#\" onClick={(e)=>removeImg(e, props.index)}>X</a>\n");
      out.write("				</div>\n");
      out.write("				<img src={props.src} width='100px'/>\n");
      out.write("			</div>\n");
      out.write("		);\n");
      out.write("	}\n");
      out.write("\n");
      out.write("\n");
      out.write("	function removeImg(e, index){\n");
      out.write("		$(e.target).parent().parent().remove();\n");
      out.write("\n");
      out.write("		let file=oriFiles[index];\n");
      out.write("		let sel_index=oriFiles.indexOf(file);\n");
      out.write("\n");
      out.write("		// 구한 순번으로 배열 요소 삭제 \n");
      out.write("		oriFiles.splice(sel_index, 1);\n");
      out.write("	}\n");
      out.write("\n");
      out.write("\n");
      out.write("	function createCategoryOption(result){\n");
      out.write("		console.log(result);\n");
      out.write("		let op=\"<option value='0'>상품분류</option>\";\n");
      out.write("		\n");
      out.write("		for(let i=0; i<result.length;i++){ //json 배열만큼 반복\n");
      out.write("			\n");
      out.write("			let category=result[i];		//카테고리 하나 꺼내기\n");
      out.write("			op+=\"<option value='\"+category.category_idx+\"'>\"+category.category_name+\"</option>\";\n");
      out.write("		}\n");
      out.write("		$(\"#category_idx\").html(op);								\n");
      out.write("	}\n");
      out.write("\n");
      out.write("\n");
      out.write("	function getCategoryList(){\n");
      out.write("		$.ajax({\n");
      out.write("			url:\"/admin/category/category_list.jsp\",\n");
      out.write("			type:\"GET\",\n");
      out.write("			success:function(result, status, xhr){\n");
      out.write("				//옵션 채우기\n");
      out.write("				createCategoryOption(result);\n");
      out.write("			}\n");
      out.write("		});\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	function previewImg(){\n");
      out.write("		for(let i=0; i<fileList.length; i++){\n");
      out.write("			let reader=new FileReader();\n");
      out.write("\n");
      out.write("			reader.onload=function(e){\n");
      out.write("				tag.push(<ImgBox key={i} src={e.target.result} index={i} />);\n");
      out.write("\n");
      out.write("				if(i>=(fileList.length-1)){\n");
      out.write("					previewRoot.render(tag);\n");
      out.write("				}\n");
      out.write("			}\n");
      out.write("			reader.readAsDataURL(fileList[i]);\n");
      out.write("		}\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	$(function(){\n");
      out.write("		// 리액트 객체 생성\n");
      out.write("		previewRoot=ReactDOM.createRoot(document.getElementById(\"preview\"));\n");
      out.write("		getCategoryList();\n");
      out.write("\n");
      out.write("		\n");
      out.write("		$(\"#file\").change(function(){\n");
      out.write("			oriFiles=fileList;			\n");
      out.write("\n");
      out.write("			for(let i=0; i<this.files.length; i++){\n");
      out.write("				fileList.push(this.files[i]);\n");
      out.write("			}\n");
      out.write("			previewImg();\n");
      out.write("			\n");
      out.write("		});\n");
      out.write("\n");
      out.write("		$(\"#bt_regist\").click(function(){\n");
      out.write("			regist();\n");
      out.write("		});\n");
      out.write("\n");
      out.write("		$(\"#bt_list\").click(function(){\n");
      out.write("			$(location).attr(\"href\",\"/admin/product/list.jsp\");\n");
      out.write("		});\n");
      out.write("		\n");
      out.write("	});\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
